name: Python tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install apt dependencies
      run: sudo apt-get update && sudo apt-get install libdbus-1-dev libdbus-glib-1-dev python3-dev
    - name: Install dependencies
      working-directory: .
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 hw_diag/. --count --max-complexity=10 --statistics
    - name: Move migrations to expected location
      run: |
        mkdir /opt/migrations
        cp -r migrations /opt/migrations/.
        cp -r alembic.ini /opt/migrations/.
        sudo mkdir /var/data
        sudo chmod 777 /var/data
    - name: Unit tests
      run: |
        pip install pytest
        pytest . --cov=hw_diag --cov=bigquery --cov-fail-under=70
